name: k8s-job
description: Runs your build step as a kubernetes job
author: https://github.com/buildkite
requirements:
  - jq
  - kubectl
  - kustomize
configuration:
  properties:
    pod-spec:
      type: string
    cleanup:
      type: boolean
  required:
    - pod-spec
  additionalProperties: false
