name: k8s-job
description: Runs your build step as a kubernetes job
author: https://github.com/buildkite
requirements:
  - jq
  - kubectl
  - kustomize
configuration:
  properties:
    metadata:
      type: object
      properties:
        annotations:
          type: object
    pod-spec:
      type: string
    cleanup:
      type: boolean
    mount-source:
      type: boolean
    full-debug:
      type: boolean
  required:
    - pod-spec
  additionalProperties: false
