#!/usr/bin/env bash
set -euxo pipefail
cd "$(dirname "$0")/.."

POD_SPEC=$(jq -cr '.["pod-spec"]' <<< "${BUILDKITE_PLUGIN_CONFIGURATION}")

cat <<EOF | kubectl create job -f -
apiVersion: batch/v1
kind: Job
metadata:
  generateName: ${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_STEP_ID}-
  labels:
    service: buildkite
    pipeline: ${BUILDKITE_PIPELINE_SLUG}
    step: ${BUILDKITE_STEP_ID}
spec:
  backoffLimit: 3
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        service: buildkite
        pipeline: ${BUILDKITE_PIPELINE_SLUG}

        step: ${BUILDKITE_STEP_ID}
    spec: ${POD_SPEC}
EOF

kubectl logs -l step=${BUILDKITE_STEP_ID} --tail=-1 --follow=true

kubectl get -l step=${BUILDKITE_STEP_ID} job -o json
