#!/usr/bin/env bash
set -uo pipefail
cd "$(dirname "$0")/.."

CLEANUP=$(jq -cr '.["cleanup"]' <<< "${BUILDKITE_PLUGIN_CONFIGURATION}")
if [ "${CLEANUP}" == "true" ]; then
  echo "Deleting job..."
  kubectl delete -l step=${BUILDKITE_STEP_ID} job
fi
